version: "3"
services:
  core:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./.env:/opt/OLAINDEX/.env
      - ./db/database.sqlite:/opt/OLAINDEX/database/database.sqlite
    links:
      - postgres
      - redis
  
  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: redis:5.0.6-alpine
